

drop table tbl_employee if exists;

CREATE TABLE tbl_employee (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                        last_name varchar(100) NOT NULL,
                        gender varchar(100) DEFAULT NULL,
                        email varchar(200) NOT NULL,
                        PRIMARY KEY (id)
);

insert into tbl_employee(id, last_name, gender, email) values (1, 'tom', 0,'tom@qq.com');
insert into tbl_employee(id, last_name, gender, email) values (2, 'jane', 1,'jane@qq.com');
